from dataclasses import dataclass
from datetime import datetime, timezone

import nbformat


@dataclass(slots=True)
class NotebookContent:
    abstract: str
    methodologies: list[str]
    algorithms: list[str]
    datasets: list[str]
    results: str
    conclusions: str
    filename: str | None = None


def generate_title_from_abstract(abstract: str) -> str:
    if not abstract.strip():
        return "Research Analysis"

    text = abstract.strip()
    period_idx = text.find(".")

    if period_idx > 0:
        title = text[:period_idx]
    else:
        title = text[:80]

    title = title.strip()
    if len(title) > 100:
        title = title[:97] + "..."

    return title or "Research Analysis"


def _md(source: str) -> nbformat.notebooknode.NotebookNode:
    return nbformat.v4.new_markdown_cell(source)


def _code(source: str) -> nbformat.notebooknode.NotebookNode:
    return nbformat.v4.new_code_cell(source)


def bullet_list(items: list[str]) -> str:
    return "\n".join(f"- {item}" for item in items) if items else "- N/A"


def algo_stub(name: str) -> str:
    safe = name.replace(" ", "_").replace("-", "_").lower()
    return (
        f"def {safe}(data):\n"
        f'    """{name} implementation stub.\n'
        f"    Replace with actual implementation from the paper.\n"
        f'    """\n'
        f"    # TODO: implement {name}\n"
        f"    raise NotImplementedError\n"
    )


def build_notebook(req: NotebookContent) -> nbformat.notebooknode.NotebookNode:
    title = req.filename.replace(".pdf", "") if req.filename else "Research Paper"
    nb = nbformat.v4.new_notebook()

    cells = [
        _md(
            f"# {title}\n\n"
            "*Generated by [Research Notebook Generator](http://localhost:3000)*\n\n"
            f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}"
        ),
        _md("## Setup\n\nInstall and import required libraries."),
        _code(
            "# Install dependencies (works in Colab, local Jupyter, and plain Python)\n"
            "import sys\n"
            "try:\n"
            "    import numpy, pandas, matplotlib, sklearn\n"
            "except ImportError:\n"
            "    import subprocess\n"
            "    subprocess.check_call([sys.executable, '-m', 'pip', 'install',\n"
            "                           'numpy', 'pandas', 'matplotlib', 'scikit-learn'])\n\n"
            "import numpy as np\n"
            "import pandas as pd\n"
            "import matplotlib.pyplot as plt\n"
            "import matplotlib.ticker as ticker\n"
            "from sklearn.model_selection import train_test_split\n"
            "from sklearn.metrics import accuracy_score\n\n"
            "np.random.seed(42)\n"
            'print("Libraries loaded successfully.")'
        ),
        _md(f"## Abstract\n\n{req.abstract}"),
        _md(f"## Key Methodologies\n\n{bullet_list(req.methodologies)}"),
        _md(
            "## Algorithms & Techniques\n\n"
            f"{bullet_list(req.algorithms)}\n\n"
            "The cells below provide stub implementations to get you started."
        ),
    ]

    for algo in req.algorithms:
        cells.append(_code(algo_stub(algo)))

    cells += [
        _md(
            "## Datasets\n\n"
            f"{bullet_list(req.datasets)}\n\n"
            "The cell below generates synthetic data that mimics the structure "
            "described in the paper so you can run experiments immediately."
        ),
        _code(
            "# Synthetic dataset — replace with real data loading as needed\n"
            "n_samples = 1000\n"
            "n_features = 10\n\n"
            "X = np.random.randn(n_samples, n_features)\n"
            "y = (X[:, 0] + X[:, 1] > 0).astype(int)  # binary target\n\n"
            "X_train, X_test, y_train, y_test = train_test_split(\n"
            "    X, y, test_size=0.2, random_state=42\n"
            ")\n\n"
            'print(f"Train: {X_train.shape}, Test: {X_test.shape}")\n'
            "pd.DataFrame(X_train, columns=[f'feature_{i}' for i in range(n_features)]).head()"
        ),
        _md(f"## Results\n\n{req.results}"),
        _code(
            "# Reproduce key results — update metric values from the paper\n"
            "metrics = {\n"
            "    'Baseline': 0.70,\n"
            "    'Proposed Method': 0.85,\n"
            "}\n\n"
            "fig, ax = plt.subplots(figsize=(7, 4))\n"
            "bars = ax.bar(metrics.keys(), metrics.values(), color=['#6b7280', '#a855f7'])\n"
            "ax.set_ylim(0, 1.0)\n"
            "ax.set_ylabel('Score')\n"
            "ax.set_title('Method Comparison')\n"
            "ax.yaxis.set_major_formatter(ticker.PercentFormatter(xmax=1))\n"
            "for bar, val in zip(bars, metrics.values()):\n"
            "    ax.text(bar.get_x() + bar.get_width() / 2, val + 0.01,\n"
            "            f'{val:.0%}', ha='center', va='bottom', fontweight='bold')\n"
            "plt.tight_layout()\n"
            "plt.show()"
        ),
        _md(f"## Conclusions\n\n{req.conclusions}"),
        _md(
            "## References\n\n"
            f"- Source paper: **{title}**\n"
            "- Datasets: " + (", ".join(req.datasets) if req.datasets else "See paper") + "\n"
            "- Add full citations here.\n\n"
            "---\n"
            "**Disclaimer:** Educational summary only. This is not a substitute for the original paper. "
            "Verify details and consult the original work before implementation decisions."
        ),
    ]

    nb.cells = cells
    nb.metadata["kernelspec"] = {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3",
    }
    nb.metadata["language_info"] = {"name": "python", "version": "3.10.0"}
    nb.metadata["colab"] = {"name": f"{title}.ipynb", "provenance": []}
    return nb


def notebook_to_markdown(req: NotebookContent) -> str:
    title = req.filename.replace(".pdf", "") if req.filename else "Research Paper"
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    sections = [
        f"# {title}\n\n*Generated {ts} · [Research Notebook Generator](http://localhost:3000)*",
        f"## Abstract\n\n{req.abstract}",
        f"## Key Methodologies\n\n{bullet_list(req.methodologies)}",
        "## Algorithms & Techniques\n\n"
        + bullet_list(req.algorithms)
        + ("\n\n" + "\n\n".join(
            "```python\n" + algo_stub(algo).rstrip() + "\n```" for algo in req.algorithms
        ) if req.algorithms else ""),
        "## Datasets\n\n" + bullet_list(req.datasets) + "\n\n```python\n"
        "import numpy as np\nimport pandas as pd\n\n"
        "# Replace with real data loading\nX = np.random.randn(1000, 10)\n```",
        f"## Results\n\n{req.results}",
        f"## Conclusions\n\n{req.conclusions}",
        "## References\n\n"
        f"- Source: **{title}**\n"
        "- Datasets: " + (", ".join(req.datasets) if req.datasets else "See paper")
        + "\n\n---\n"
        + "*Disclaimer: Educational summary only. Not a substitute for the original paper. "
        + "Verify details and consult the original work.*",
    ]
    return "\n\n---\n\n".join(sections) + "\n"